
services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} && psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1'"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
        postgres:
          condition: service_healthy
    env_file:
      - .env